### ISSUE TITLE
dropdown at navbar hidden by slider (v0.96)

### ISSUE THREAD

**Issue by mylastof** [Dogfalo/materialize#1076]
![navbar](https://cloud.githubusercontent.com/assets/2387514/6957718/fe185370-d929-11e4-9663-70197aa005a7.png)

**Comment by Dogfalo** [comment]
Dropdown is a child of its parent, so if you give your navbar a higher z-index than what it is at currently, it should fix it.

**Comment by patou** [comment]
I have the same problem, and changing the z-index not change the display.
The nav bar isn't fixed.

**Comment by Scottjbrownlee** [comment]
I have the same problem and the z-index is not making a difference.  It seems making this a child of the parent is interfering with the ability to display the dropdown.  I've attached the parent (with hover), when you click it and what appears in 0.96.0 and what used to appear in 0.95.3
![bug1](https://cloud.githubusercontent.com/assets/11063258/6988216/164fc448-da1d-11e4-979c-fea12533c4c2.jpg)
![bug2](https://cloud.githubusercontent.com/assets/11063258/6988218/18c5c7c2-da1d-11e4-9f59-47d4562bbd0a.jpg)
![bug3](https://cloud.githubusercontent.com/assets/11063258/6988237/4d81611a-da1d-11e4-9dd7-b807585b11e1.jpg)

**Comment by patou** [comment]
I Found the problem, you must not have this css rule : 
<code>
nav {
   overflow: hidden;
}
</code>

**Comment by olivier67** [comment]
to fix this I added to my css :
`.dropdown-button { overflow: visible;}`

**Comment by acburst** [comment]
This seems to be a nav overflow issue so I'm closing this.

**Comment by dphopkins** [comment]
Still having issues with this as of 0.97.5. I'm using 0.95.3 to get dropdowns to work at all. The overflow changes aren't working for me. Should I reopen this or make a new issue?
