### ISSUE TITLE
Open modal multiple times and closing it leaves behind the dark overlay permanently

### ISSUE THREAD

**Issue by carlosperate** [Dogfalo/materialize#1647]
So if a modal is opened multiple times, and then exited only the latest overlay is removed and all other stay there permanently.

To test you can go to http://materializecss.com/modals.html and in the javascript console just run `$('#modal1').openModal();` multiple times. You can see that after clicking any of the modal options only one overlay is removed.

**Comment by pascal-de-ladurantaye** [comment]
Problem is that the lean-overlay is not reused if it exists:

Following: The generated html after opening the modal 4 times.

```html
<div class="lean-overlay" id="materialize-lean-overlay-1" style="z-index: 1002; display: block; opacity: 0.5;"></div>
<div class="lean-overlay" id="materialize-lean-overlay-2" style="z-index: 1004; display: block; opacity: 0.5;"></div>
<div class="lean-overlay" id="materialize-lean-overlay-3" style="z-index: 1006; display: block; opacity: 0.5;"></div>
<div class="lean-overlay" id="materialize-lean-overlay-4" style="z-index: 1008; display: block; opacity: 0.5;"></div>
```

**Comment by carlosperate** [comment]
It might be relevant to mention that previous behaviour probably did reuse the overlay, as if you opened 2 different modals and then closed 1 one of them it would remove all the overlay completely and you would end up with the other modal still present in the page without the dark overlay.
https://github.com/Dogfalo/materialize/issues/1512

**Comment by pascal-de-ladurantaye** [comment]
Couldn't each modal have it's own overlay reference and reuse it when it is opened a second time?

However, this would have the (probably already existing) side-effect of having a darker overlay when opening 2 different modals at the same time.

**Comment by carlosperate** [comment]
Yeah, I think we need to be able to easy track the number of overlays opened and the cleanest way could probably be to add a `data-` attribute to a single overlay.

The current modal add overlay code can be see in the [leanModal.js - L23-61](https://github.com/Dogfalo/materialize/blob/19029513c79fc6edd470e478b56c016ee18b9ce9/js/leanModal.js#L23-61) file. As you have shown, the code will add a new `div` with a unique identifier each time a modal is opened. I think instead it could add a single `div` with a unique identifier (so try to `getElementById ` with the unique identifier and only add the new `div` to the DOM if not found), and then edit an html5 `data-` attribute with a counter of how many modals remain opened (so [openModal](https://github.com/Dogfalo/materialize/blob/19029513c79fc6edd470e478b56c016ee18b9ce9/js/leanModal.js#L10) adds to the counter, and [closeModal](https://github.com/Dogfalo/materialize/blob/19029513c79fc6edd470e478b56c016ee18b9ce9/js/leanModal.js#L98) subtracts from the counter), which will then only remove the overlay when the counter reaches 0.

In essence having something like:

```
<div class="lean-overlay" id="materialize-single-lean-overlay" data-overlay-counter="3"></div>
```

The main reason I suggest to add the counter as an attribute is because then other components (like the side menus, date pickers, or whatever) can just reuse the same component.

Otherwise the variable [_lastID](https://github.com/Dogfalo/materialize/blob/19029513c79fc6edd470e478b56c016ee18b9ce9/js/leanModal.js#L3) could be replaced to an internal overlay counter.

**Comment by carlosperate** [comment]
Or the since the current code edits the modal `div` `display` option between `none` and `block` it could easily check if it is already `block` do not add an extra overlay in that case.

**Comment by pascal-de-ladurantaye** [comment]
The problem i see with this implementation is the following:

 - We open the same modal 4 times : data-overlay-counter="4"
 - We close the modal : data-overlay-counter="3"
 - There is no modal left but the overlay is still there.

We need a way to distinguish opening the modal when it is already opened and opening it when its closed IMO.

**Comment by carlosperate** [comment]
>We need a way to distinguish opening the modal when it is already opened and opening it when its closed IMO.

Check my last message. I would submit a pull request for that quick fix, but I do not have any of the build requirements to test it, so I hope somebody else could try to implement that.

**Comment by pascal-de-ladurantaye** [comment]
You are totally right. I will try to make a pull request for this tonight.

**Comment by pascal-de-ladurantaye** [comment]
Do we really want to be able to open an already opened modal?

If it is not the case, we could simply check if the modal is already opened at the beginning and return if it is.

Please tell me what you think about this.

**Comment by carlosperate** [comment]
Check how the z-index is calculated, if you have multiple modals opened and try to reopen one that is a level below, then z-index still needs to be recalculated.

**Comment by carlosperate** [comment]
hey @pascal-de-ladurantaye, were you able to make any progress on this?

**Comment by pascal-de-ladurantaye** [comment]
For the first time in years, I didn't have time to touch my computer for a full weekend 0_o
I was planning on making the setup tonight and make a first attempt to a fix.

**Comment by pascal-de-ladurantaye** [comment]
@carlosperate I did not test with bottom-sheet modals but I assume it will react the same.

**Comment by cryptoquick** [comment]
Looking forward to seeing this fix in the next release. :+1:

**Comment by pascal-de-ladurantaye** [comment]
@Dogfalo @acburst Is there something wrong with the pull request i submitted^ I see you are merging other PR but not this one.

**Comment by Dogfalo** [comment]
It takes time to go through PR to check code quality and whether or not
they work so we just did not get to yours yet. We will take a look soon.

**Comment by alexofob** [comment]
This issue still persist. When are we getting a fix.
Thanks

**Comment by alexofob** [comment]
I am not not sure whether this issue is specific to meteor. But below is a simple fix I did:

$('.modal-trigger').leanModal(
      dismissible: true
      complete: ->
        $('.lean-overlay').remove()

**Comment by JonathanGuo** [comment]
I actually submitted a pull request on Jun 25. But no response at all. Now it looks like it has conflicts to current code.

Anyway I still implement the code in my project to fix the issue. If you guys have some issue you can simple use my code. #1590 

Copy the code and using grunt to recompile the materialize.js and materialize.min.js.

**Comment by gg4u** [comment]
Is this issue solved?
I keep to see modal _IDs duplicated.

Also, how to set dimissable without calling a closeModal() or openModal() actions?

Suppose you want to block a modal for a call to action.
As a callback, modal become updated.
You don't want to close it, and allow user read update.

Then, I simply would like to click on the lean-modal background, but it stays blocked.

I tried to override dimissable click on the layer but it did not work.
```javascript
    $modal = $('#modal-call-action'),
    $overlay = $('<div class="lean-overlay"></div>'),
    $overlay.click(function() {
          $modal.closeModal({dismissible : true, complete: function() { $('.lean-overlay').remove() }});
        });
```

**Comment by romant** [comment]
confirming that @alexofob's workaround of adding the following to initialisation works.

```
complete: function () {
      $('.lean-overlay').remove();
    }
```
look forward to this not being necessary.

**Comment by bstump** [comment]
Adding the "complete" initialization *only* didn't work for me. So, I added that, but I also had to go in and add this to "leanModal.js". Sucks that I had to change the source, but it's what had to be done. Here's the fix that I used, in hopes that it help someone else having the issue:

First, replace '$("body").append($overlay)' in 'materialize.js' with:

if ($('.lean-overlay').length > 0) {
    $overlay.show();
} else {
    $("body").append($overlay);
}

Second, replace "_lastID++;" with:

if ($('.lean-overlay').length > 0) {
    _lastID++;
}

I found that this isn't an issue if you're using a *single* jQuery selector (and ID), but it becomes an issue when you are doing a multi-selector (like a class selector such as '.modal-trigger'). It also seems to be an issue if you're loading AJAX content into the modal. Here's the code I was having issues with:

    // Trigger view invoice modal
    modal_invoice_id = null;
    $('.modal-trigger').leanModal({
        ready: function() {
            // Show loading text
            $('#view-invoice-data').html('<em>Loading invoice...</em>');

            // Get recent transactions
            $.getJSON('/invoicing/view/'+modal_invoice_id, {}, function(resp) {
                // Check success / fail
                if (resp.status === 'success') {
                    // Prepend new MID
                    $('#view-invoice-data').html(resp.data);
                } else {
                    $('#view-invoice-data').html('<em style="color:#ff0000;">Error (VI.001).</em>');
                }
            })
            .fail(function() {
                // Show error
                $('#view-invoice-data').html('<em style="color:#ff0000;">Error VI.002).</em>');
            });
        },
        complete: function() {
            // Show loading text
            $('#view-invoice-data').html('<em>Loading invoice...</em>');
            $('.lean-overlay').remove();
        }
    }).click(function() {
        modal_invoice_id = $(this).attr('invoice-id');
    });

**Comment by bstump** [comment]
What the code above does is check if there's already a "lean-overlay" on the page and then, instead of appending another one, it will just "show" the one that's already there.

**Comment by pascal-de-ladurantaye** [comment]
This has been fixed for over 8 months.... If only they merged the PR.

*Pascal de Ladurantaye*
*Génie Logiciel 4e année*
*VP-Technologie du CEGE*
*École Polytechnique de Montréal*

**Comment by bstump** [comment]
I had to do a LOT more than "remove lean-overlay". Looks like it's an issue when you use a jQuery multi-select and/or when you add content to the modal through AJAX. I have attached a file with the fix.
[leanModal.js.zip](https://github.com/Dogfalo/materialize/files/99542/leanModal.js.zip)

**Comment by bstump** [comment]
@pascal-de-ladurantaye I just grabbed leanModal.js from the master repo and it's still broken. My zip file above fixes it. What branch is this issue resolved in?

**Comment by pascal-de-ladurantaye** [comment]
#1691

**Comment by isaachinman** [comment]
Why has this not been merged? Adding the removal of lean-overlay to `complete` is _such_ and easy fix, cmon guys.

**Comment by carlosperate** [comment]
While I do agree this should have been fixed a while ago it's not as simple as just removing the overlay. You can have multiple modals opened, each overlaying the previous modal, what happens then when you reopen a modal that was hidden behind a newer one? Also, if you close any of those, only it's relevant overlay should be removed and the rest left behind.

All that said, this behaviour has been taken in consideration and fixed in https://github.com/Dogfalo/materialize/pull/1691 ...

**Comment by isaachinman** [comment]
Ah yes, wasn't aware of those complications. At any rate, cheers, I see #1691 is due to be merged imminently.

**Comment by JonathanGuo** [comment]
To anyone who wants to solve this problem by using my code and recompiling the package. please checkout the file https://github.com/JonathanGuo/materialize/blob/Fixed-duplicated-leanModal-overlays/js/leanModal.js

I created a pull request #1590 ages ago and never been merged. This piece of code perfectly solved this issue. We already used this in our product. I am not going to resubmit my code and hope the code to be merged.

**Comment by samudranb** [comment]
@JonathanGuo could you please help me understand how I could apply your fix?

I'm using the materialize:materialize package on meteor, and I can't find the leanModal.js file anywhere. Do I have to remove the package, download the materialize, and your file, and add it back? That might cause other packages which have dependency on materialize to break. :cry:

**Comment by samudranb** [comment]
Honestly though, I do wish this issue was closed if the pull request is valid!

**Comment by JonathanGuo** [comment]
@samudranb I know it's a pain. So in our project I folked the Materializecss and applied the changes. Then I have my own  gruntfile.js to build the js file.  In this way there is no conflict but every time you update the Materializecss package, you need to run your own gruntfile.js to generate the file.

For your gruntfile, you can simply copy https://github.com/Dogfalo/materialize/blob/master/Gruntfile.js and change the leanModel.js route to yours.

**Comment by samudranb** [comment]
Thanks @JonathanGuo ! I'll check it out

**Comment by samudranb** [comment]
Thanks @JonathanGuo ! I'll check it out

**Comment by Metisse** [comment]
hi ! i found a solution for me maybe it's work for you : 

   ** $(document).ready(function(){
                $('#modal').click(function() {
                     $('#modal1').openModal();
                });
                if ($('body').css(''))
                {
                    $('.lean-overlay').remove();
                }
            });
**

**Comment by Sc07713** [comment]
Hi there, I thought I would just add my fix that I placed in materialize.js within the openModal extension.

If there is more than 2 layers, it will just delete them, its not the most efficient method but it seems to operate better for me than the fix to leanModal.js.

`//this function is to help count and kill lean overlay duplicates
function removeLeanOverlayDup() {
    
    $('.lean-overlay').each(function (i, obj) {
        if (i > 1) {
            $('.lean-overlay').slice(i).remove();
        }
        });
    
};`

**Comment by carlosperate** [comment]
So what happens if you have one modal opened, and then a different one opens on top?

**Comment by Sc07713** [comment]
It only ever has two overlays max. 0 and 1 in the .each statement. 

If there was a 3rd one I would bump it up to 2. However I think it may struggle if there were anymore than 2.

It seems to work better than the leanModal fix for the time being. (well atleast for my implementation)

The lean modal fix was buggy as, and for some weird reason was shutting down my modals and overlays for no reason that I could see.

**Comment by gubi** [comment]
Above patches doesn't fix for me.
I have this environment:
* an _ever-present_ **button** that trigger
 * a **modal with button** that launch
   * an **async call that** on success **close modal and change page contents**.

So, opening and closing recursively modals, it remembers the last ".lean-overlay" ID and then uses another new one. This cause the issue!
I think that a simple static "lean-overlay", switched on and off, could be a better lightweight approach...
Anyway, I used this simple patch and on Firefox 44.0 seems to work:
``` javascript
$('.modal-trigger').leanModal({
    dismissible: true,
    opacity: 0.5,
    in_duration: 300,
    out_duration: 200,
    ready: function() {
        if($(".lean-overlay").length > 1) {
            $(".lean-overlay:not(:first)").each(function() {
                $(this).remove();
            });
        }
    },
    complete: function() {
        $(".lean-overlay").each(function() {
            $(this).remove();
        });
    }
});
```

**Comment by Krissams** [comment]
Try this one guys,
`  	$(document).ready(function(){
  	  $('.modal-trigger').leanModal();
  	});
`

**Comment by ceeeff** [comment]
Not sure if this is the same problem I was having (sounds the same). I resolved by using unbind() before calling.

**Comment by jumbosushi** [comment]
@gubi's example did the trick for me. Hope they will patch this at some point tho.

**Comment by gdoron** [comment]
@Dogfalo @acburst Are you still actively maintaing your awesome library?
If yes, please merge the pull request, it's more than a year since it was opened.
If no, please add new collaborates to the project, I'm sure there're many users who can and want to make this project continue. 

Thoughts? @pascal-de-ladurantaye ?

**Comment by jhillhouse92** [comment]
@Dogfalo What's the status with this issue?

**Comment by tomscholz** [comment]
@gdoron The PR was merged. And [here](https://github.com/Dogfalo/materialize/issues/4423) something about the state of this project
Does the issue still occur to you?
@jhillhouse92 Thats the question ;)

**Comment by jhillhouse92** [comment]
@tomscholz Indeed it is, glad traction is starting to take place :)... with 25k+ stars that's a pretty important library to lots of people. Lets keep it that way.

**Comment by tomscholz** [comment]
Closed due inactivity and being solved. https://github.com/modweb/meteor-materialize-connection-status/pull/2
