### ISSUE TITLE
Error Compiling _color.scss

### ISSUE THREAD

**Issue by mrsd88** [Dogfalo/materialize#193]
Hi guys, I have problem when I did first compile SASS using Scout App. There is log:
error materialize.scss (Line 11 of _color.scss: Invalid CSS after " "lighten-5"": expected ")", was ": #fdeaeb,")

what should I do? Sorry, I'm newbie still learning with sass. 
I'm waiting for your help. :)

**Comment by 3amsleep** [comment]
i came across this issue using rails, solved by updating the sass-rails gem un the bundle

    gem 'sass-rails', '~> 5.0'

**Comment by kaleb4eg** [comment]
I have same issue and updating "sass-rails" didn't solve problem. Solved problem updating "sass" gem directly as @bogdanteodoru mentioned.

**Comment by blackblood** [comment]
I updated my sass-rails version to 5.0.3 and its still not working

**Comment by Dogfalo** [comment]
Read the post above yours

**Comment by sameera207** [comment]
I had the same issue and was able to resolve it by the help of comments from @burabure and @bogdanteodoru, coz it didnt solve the issue by only updating the `sass-rails`, 

#Gem file
`
gem 'sass'
gem 'sass-rails', '~> 5.0'
`
and 

`bundle update`

that solved the problem :dancer:

**Comment by rangeles-localytics** [comment]
Will having 2 versions of 'sass' cause issues? 

I have versions: sass (3.4.14, 3.2.19) installed.

**Comment by Dogfalo** [comment]
As long as you use the higher version to compile it should be fine
