### ISSUE TITLE
Upgrading to 0.97.1 from 0.97.0 fails meteor app

### ISSUE THREAD

**Issue by milanzigmond** [Dogfalo/materialize#2037]
Just saw and upgrade this morning you pushed, but after update my app was a bit confused :) http://prntscr.com/8g3z9p  Just to let you know. Had to go back to 0.97.0. Great work otherwise with Materialize!

**Comment by lampe** [comment]
same problem here 

http://i.imgur.com/8ksDN3P.png

**Comment by serkandurusoy** [comment]
Yep, upgrading to 0.97.1 on *Meteor* breaks the whole app!

**Comment by serkandurusoy** [comment]
@Dogfalo the problem is the minimized javascript. If you point `package.js` to the (unminified) javascript in the `dist` folder, the app works. But if you point it to either one of the minified ones, it wreaks havoc!

**Comment by serkandurusoy** [comment]
@Dogfalo I've created a quick fix PR, but you need to also either tag that as a new release or publish manually.

**Comment by mrvol** [comment]
I had some problem. I resolve it now. I think, problem is changes in line 255 of version 0.97.1:

-;Materialize = {};
+;window.Materialize = {};

So, next function, "Materialize.guid = (function() {" raise error. 

I do next.
> meteor remove materialize:materualize
> meteor add materialize:materialize@0.97.0
> meteor reset

But, meteor add version materialize:materialize@0.97.1.
I find file app/.meteor/versions and change line

- materialize:materialize@0.97.1
+ materialize:materialize@0.97.0

Then,
> meteor

And now all is ok.
So, link not work "https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.1/js/materialize.min.js" too.

P.S.: Sorry for english.

**Comment by serkandurusoy** [comment]
@mrvol you could edit your `.meteor/packages` file and change `materialize:materialize` to `materialize:materialize@=0.97.0` for the time being. Then a `meteor update` will ensure your version *stays* at `0.97.0` until the latest one gets fixed.

**Comment by keyscores** [comment]
+1 replicated issue with upgrade.

**Comment by bgunter** [comment]
Sending Meteor crazy when I upgrade from 97.0 to 97.1.  I haven't quite figured out what the problem is.   Pointed package.js to the dist and problem remains.   I'll let you know if I figure it out.

**Comment by nelreina** [comment]
same problem here I'll wait for update / going back to 0.97.0 :(. 

javascript console 
<img width="1267" alt="screen shot 2015-09-15 at 19 36 56" src="https://cloud.githubusercontent.com/assets/5773049/9884776/e8e68bbc-5be1-11e5-9d76-d687dfef19a3.png">

**Comment by FreefallGeek** [comment]
Just stopping in to confirm the issue above. I get the exact same console output as nelreina. I rolled back to 97.0 to resolve but that was a pretty crippling update.

**Comment by rwatts3** [comment]
It amazes me that it's going on 2 days of the initial post with no response. If you are going to implement breaking changes please look out for the devs in the community when issues like this arise.

**Comment by msolters** [comment]
I noticed this exact issue 16 days ago while working with a local fork.  I thought it was something *I* had done wrong or misconfigured locally.  So the error is at least that old FWIW.

**Comment by keyscores** [comment]
@Dogfalo is it possible to merge the PR provided @serkandurusoy ?

**Comment by JulianKingman** [comment]
Same issue here.

**Comment by FelipeRosa** [comment]
+1

**Comment by tdbs** [comment]
:+1: 

Same here, reverted back

**Comment by joshfttb** [comment]
Same here,  reverted back after much ado.

**Comment by rwatts3** [comment]
Still no response ? Are you serious

**Comment by serkandurusoy** [comment]
Guys, until @Dogfalo gets back to us, we could temporarily fork the repo and publish it on atmosphere.

Of course that's a double edged sword. It *will* be abandoned, will definitely create some confusion over why official package is so broken and the presence of unbroken unofficial packages etc.

So what do you guys think?

**Comment by FreefallGeek** [comment]
I'm fine just backdating to 97.0 until a fix is uploaded.

**Comment by bgunter** [comment]
97.1 Seems to working okay for me when downloaded and used as a local package after `meteor remove materialize:materialize`

**Comment by JulianKingman** [comment]
@serkandurusoy Let's hold out a bit and see what he says, I always find it annoying when there are dozens of packages for the same thing.

**Comment by serkandurusoy** [comment]
Yep, I'm also hesitant to make such move. It is also very sad to see the current state of the situation :(

**Comment by chiwaili** [comment]
Same here, i'm locking it at `meteor add materialize:materialize@=0.97.0` for now. 
Thanks for your hard work folks

**Comment by serkandurusoy** [comment]
Guys, you can go show your support/+1's over at #2056 and for those of you who use a local clone of the repo, the fix suggested there is the safest and most complete I've seen.

**Comment by katrotz** [comment]
same as @nelreina. Downgraded to 0.97.0

**Comment by rwatts3** [comment]
@Dogfalo 
This issue has gone on for nearly 21 days with no response from the team. I am curious as to why such a great project has not attempted to respond with a simple, We're looking into it, or Pull requests will be accepted. To leave the community pondering a solution for this long could really loose a lot of support.

**Comment by Dogfalo** [comment]
Hey Ryan, rest assured we have seen the many reports regarding this issue.
We have been busy closing a lot of other issues. Please use the old release
until we can thoroughly test the new fix.

**Comment by rwatts3** [comment]
Thank you for the follow up.

**Comment by delvedor** [comment]
Same issue here!

**Comment by Charpeni** [comment]
Same issue, downgraded to 0.97.0.

**Comment by Dogfalo** [comment]
fixed in #2056

**Comment by ntoka** [comment]
When are you planning on pushing this fix to Atmosphere? Downloading 0.97.1 via meteor update still gets the broken version

**Comment by rwatts3** [comment]
Agreed, still getting the same issue.

**Comment by genyded** [comment]
+1 here too = still waiting on a fix and with all the needed recent meteor updates managing this exception is a bit of a pain

**Comment by genyded** [comment]
Also as far as I can see all the issues related to this fix are CLOSED so hopefully someone is looking into it

**Comment by Charpeni** [comment]
Yeah a fix that'd be great.

**Comment by keyscores** [comment]
@Dogfalo thanks for the patch. Can you please publish on atmosphere?

**Comment by Dogfalo** [comment]
When our next release comes out it will be have the fix.

**Comment by rwatts3** [comment]
Ok let me step in and say something about this. It has been over 1 month of
a release that your team introduced which introduced breaking changes for
the entire meteor community. We have clients and projects depending on your
project. This is simply unsatisfactory . And shows a lack of support to the
community. It wouldn't be right for me to sit back and pretend that this is
ok.

This is completely wrong and you should meet with your team to find a
better workflow to prevent this from happening again in the future. I think
materializecss is a great framework which is why I'm taking the time to
write this critical piece of advice.

Going forward never leave the community lagging behind for over a month
while you "figure out" a way to fix the issue. A fix was posted and it took
several weeks to review then approved the patch and took several more weeks
to even respond to the community. I'm not saying this is the case for every
real ease but certainly you should take a more direct action when your
release introduces breaking changes.

According to Sym Versioning. Only latter steps should introduce breaking
changes. Such as 1.0.0.

Version 0.1.0 should introduce minor updates but no breaking changes.

And version 0.0.1 updates should be patch fixes. There is no reason this
should not have been published to 0.97.2 when the fix was approved.

I'm sure your team is aware of the symver process which is why it doesn't
make sense the lack of communication your team had for the community during
this process.

As a meteor developer there are several of us in the community that work
really hard night and day to ensure we stay in touch with our fellow
developers in the community.

Ryan.

**Comment by Charpeni** [comment]
0.97.2 on atmosphere !

**Comment by nelreina** [comment]
Thank you!!! Finally it works.

**Comment by genyded** [comment]
Yes - this root issue seems fixed in 0.97.2, but selects are broken (see [#2665](https://github.com/Dogfalo/materialize/issues/2265) and there are a ton over Roboto font version warnings in the console. And that's just in the first 5 minutes of using the new version. If I go back to 0.97.0 everything works and there are no font version issue warnings. Staying on 97 for now.

**Comment by JulianKingman** [comment]
@rwatts3 I agree, this fix took longer than it needed to, it shakes developer confidence.

**Comment by justswim** [comment]
Is this fixed now? I see it's closed, but today I tried updating Materialize to 0.97.4, and it broke my app. I ended up downgrading back to 0.97. Am I doing something wrong here?

Thanks for your help!

**Comment by ntoka** [comment]
As far as I know upgrading to 0.97.3 works fine. Have not checked .4. Actually I am still sticking to 0.97.0 because even though app does start when using 0.97.3 - some CSS that's working on .0 version is broken on .3.

**Comment by keyscores** [comment]
0.97.3 works for me.
However
0.97.4 is broken with a similar error.

**Comment by Dogfalo** [comment]
We'll fix this soon.
