### ISSUE TITLE
Carousel not draggable with the mouse

### ISSUE THREAD

**Issue by schemetastic** [Dogfalo/materialize#2533]
I'm using Firefox with Ubuntu, when i drag the carousel with the mouse does not work, instead drags the image as a file, and the dragging starts until i release the mouse.

This might help: <a href="http://stackoverflow.com/questions/12906789/preventing-an-image-from-being-draggable-or-selectable-without-using-js" target="_blank">Preventing an image from being draggable or selectable without using JS</a>

**Comment by globlee** [comment]
This is still a problem in Firefox. Works in chrome though. I wouldn't mind trying to fix it if anyone knows what exactly is the problem with Firefox here. 
https://jsfiddle.net/rdy47a4k/7/

**Comment by globlee** [comment]
Solution is to add `draggable="false" ` attribute to each image in the carousel. I will try to submit a PR but it looks like there is a lot on the queue as is.

**Comment by acburst** [comment]
Fixed in 5d68686

**Comment by Jujunol** [comment]
Just tried it on Chrome, Opera, and IE but still experiencing the issue
