### ISSUE TITLE
Required option not working with 'materialized' selects?

### ISSUE THREAD

**Issue by neFAST** [Dogfalo/materialize#2536]
Here is a demo page reproducing the issue: 
http://codepen.io/julienM/pen/mVEKRK

Submit once and you'll get the popup for the "browser default" <select>.
Then give a value to that <select> and submit again: no popup on the 2nd <select>
If you look at the logs:
An invalid form control with name='' is not focusable.

**Comment by TyrionGraphiste** [comment]
Hi, I add the required attribute on the input when it's automatically generated. I'll synchronize the PR when I will have fixed another issue.
The fix is working on Firefox, but on Google Chrome, Opera there is the same issue you encountered.

On Safari and IE (< 10) there is simply no support.

**Comment by ferchoman09** [comment]
I need 'The required' validation working in Google Chrome.

**Comment by stap123** [comment]
This is also linked to #3440. I have posted a temporary workaround for anyone still struggling.

**Comment by neFAST** [comment]
@stap123 Can you show a codepen demonstrating your fix?
I updated mine and, unless I misunderstood your suggestion, it doesn't work.
http://codepen.io/julienM/pen/mVEKRK

**Comment by Dogfalo** [comment]
Fixed in dbdd869bc929cf124757eb22d3694dc5d746c7e0

**Comment by Jeroenkeesom** [comment]
the problem is still here with V1.0.0, but when adding CSS to my own (s)css (as per Fixed in dbdd869) the issue is resolved. 
is this something i'm doing wrong?

**Comment by evansharp** [comment]
Ditto the issue is still present. @JulienMaille codepen is exactly the issue I am encountering on v1.0.0.
