### ISSUE TITLE
Icon before select in form overlapping

### ISSUE THREAD

**Issue by vincentcox** [Dogfalo/materialize#2924]
I can't get an icon before a select box like the normal input fields.
![screen shot 2016-03-17 at 20 26 15](https://cloud.githubusercontent.com/assets/9286611/13858379/b30eb856-ec7e-11e5-83f0-80cc66b968cc.png)

code:
```
                        <div class="input-field col s12 blue-text text-lighten-1">
                          <i class="material-icons prefix">receipt</i>
                          <select>
                            <option value="" disabled selected>Method</option>
                            <option value="post">Post</option>
                            <option value="get">Get</option>
                          </select>
                          <label>The method that is used while sending the parameter</label>
                        </div>
                    <script>
                    $(document).ready(function() {
                      $('select').material_select();
                    });
                    </script>
```

Is it a bug or is there a mistake in my code?

**Comment by pheliperocha** [comment]
It's look select element didn't support prefix icons yet

**Comment by acburst** [comment]
Fixed in 1090e81df399c2a6ae05eb1a8a347dcce152785b

**Comment by vincentcox** [comment]
<img width="772" alt="screen shot 2016-03-18 at 10 32 04" src="https://cloud.githubusercontent.com/assets/9286611/13873883/afd10c7c-ecf4-11e5-967a-7cde1d489ffc.png">
Still not fixed unfortunately. Or is it my code?

**Comment by vincentcox** [comment]
Nevermind, when I add
```
  <style>
  .prefix ~ .select-wrapper {
margin-left: 3rem;
  width: 92%;
 width: calc(100% - 3rem);
}

.prefix ~ label {
  margin-left: 3rem;
}

  </style>
```

It works. I have the latest version included though.
