### ISSUE TITLE
Disabled buttons are not styled due to missing comma

### ISSUE THREAD

**Issue by MrSauceman** [Dogfalo/materialize#2998]
Commit: 0005bcd8509a83541f50a2f2cab0ceed38d09a58
File: sass/components/_buttons.scss
Author: @soniabrami 

This commit leaves out a comma on line 21, which breaks the styling of disabled buttons.

**Comment by acburst** [comment]
Thanks for catching this.

Fixed in 80d8020

**Comment by jlebras** [comment]
For production environments should we use /dist or /bin folder ? 
Because in the dist folder it's not fixed.
