### ISSUE TITLE
Options passed to the dropdown are not being accounted for.

### ISSUE THREAD

**Issue by stickboywarren** [Dogfalo/materialize#3417]
The options passed to the dropdown are being overwritten by the defaults because the options parameter and the variable in the "this.each" function are both named "options."  This change happened in this commit:  

https://github.com/Dogfalo/materialize/commit/51f3b11b3cf8a042a5be709e4c2bd5a7e9d34c4a
The easiest way to fix this is to change the "options" parameter to "_options."

I'll submit a PR for this request.

**Comment by eboye** [comment]
I was just looking for an answer on why after version upgrade my dropdown stopped working on hover 😄

**Comment by dgonzalezr** [comment]
Damn!, I was going crazy here 'cuz the same reason :stuck_out_tongue:, after upgrade my dropdowns ignored whatever the option says.

**Comment by acburst** [comment]
Fixed in 2b32ca4.

Thanks for catching this!

**Comment by stickboywarren** [comment]
@acburst, no problem.  : )  Glad it was an easy fix.

**Comment by dgonzalezr** [comment]
Still having problems with options when creating dropdowns dynamically (e.x. belowOrigin = true, it's appearing hover the button not matter what).. I'm using Materialize with AngularJS, and I have a directive to initialize the drop down element, passing the options as attributes.. Already try `belowOrigin` and `beloworigin`.. neither of them worked :disappointed: 

```html
<a class="drop-down btn" data-activates="app-languages"
    data-item-alignment="right" data-constrain-width="true" data-below-origin="true">
```

```javascript
( function () {
    'use strict';

    angular
        .module( 'app.common' )
        .directive( 'dropDown', dropDownFunc );

    dropDownFunc.$inject = [ '$document' ];

    /* @ngInject */
    function dropDownFunc( $document ) {
        var directive = {
            restrict: 'C',
            link: linkFunc,
        };

        return directive;

        function linkFunc( scope, elem, attr ) {
            $document.ready( function () {
                elem.dropdown( {
                    alignment: attr.itemAlignment,
                    belowOrigin: attr.belowOrigin,
                    constrain_width: attr.constrainWidth,
                    hover: false
                } );
            } );
        }
    }
} )();
```

**Comment by dgonzalezr** [comment]
Instead, if I use:
```html
data-beloworigin="true"
```
as the doc explain, and comment in the directive:
```javascript
elem.dropdown( {
    alignment: attr.itemAlignment,
    //belowOrigin: attr.belowOrigin,
    constrain_width: attr.constrainWidth,
    hover: false
} );
```
works as expected!.. why isn't working passing the options as attribute values?? Any idea?? :confused:

**Comment by acburst** [comment]
This is only on master and isn't in the latest release. Sorry about that

**Comment by stickboywarren** [comment]
We changed the version number in the bower.json to the URL for master until a new release is built:

`
        "materialize": "https://github.com/Dogfalo/materialize.git#master",
`

**Comment by plaurent75** [comment]
the problem still occur with a NPM install. Fix seems to not be pushed to NPM.
To fix it, i have copy/paste the dropdown.js file from Git to my node_modules/materialize-css/js, then go to node_modules/materialize-css, then npm install, then grunt release, to generate the new materialize.js in the dist folder.
Probably not the better way to do it, but work on my local dev env. 
Any idea to have a better fix to be pushed on prod ?

**Comment by MaximBalaganskiy** [comment]
I prefer a patch - after module is loaded I overwrite the function with the
fixed code.
