### ISSUE TITLE
Dropdown does not move if window is resized

### ISSUE THREAD

**Issue by mitar** [Dogfalo/materialize#3833]
After a dropdown is displayed, if window is resized, the dropdown does not move to match a change in position of activator.

**Comment by phixMe** [comment]
Does anybody know if there is something that I can call to refresh the position after the page is resized?

**Comment by Dogfalo** [comment]
This has been fixed in v1-dev. Resize reflows will not mess up the dropdown position

**Comment by jacobq** [comment]
@fega Could we please re-open this since it is evidently not actually fixed?

**Comment by bekatd** [comment]
+1 still bug in 2020.

It seems this project has been abandoned since the last commit. Strange though for such a popular project
