### ISSUE TITLE
select multiple with optgroups returns wrong value

### ISSUE THREAD

**Issue by entrepenerd** [Dogfalo/materialize#4156]
# Description
Using Materialize 0.98.0, when using optgroups in a multi select it returns wrong values. Per each optgroup the values seem to get selected using an increased index value.

Might be same as select with optgroups returns wrong value #2159, but that should be fixed.

# Example

HTML with same data in two selects, one with and one without optgroups:
```
<div class="input-field col s6">
    <label>Multi-select:</label>
    <select name="ko" multiple>
        <option value="" disabled>None</option>
        <option value="aaa">aaa</option>
        <option value="bbb">bbb</option>
        <option value="ccc">ccc</option>
        <option value="ddd">ddd</option>
        <option value="eee">eee</option>
        <option value="fff">fff</option>
        <option value="ggg">ggg</option>
    </select>
</div>


<div class="input-field col s6">
    <label>Multi-select with opt-groups:</label>
    <select name="ko" multiple>
        <option value="" disabled>None</option>
        <optgroup label="Category A">
            <option value="aaa">aaa</option>
            <option value="bbb">bbb</option>
            <option value="ccc">ccc</option>
            <option value="ddd">ddd</option>
        </optgroup>
        <optgroup label="Category B">
            <option value="eee">eee</option>
            <option value="fff">fff</option>
            <option value="ggg">ggg</option>
        </optgroup>
    </select>
</div>
```

Initialize the selects:

```
$('select').material_select();
```

Reproduce:

- Select aaa,bbb,ccc in first select. All is fine.

- Select aaa,bbb,ccc in second select. bbb,ccc,ddd are returned as values...

Start all over again by refreshing the form.

- Select eee in second select, ggg is returned as value...
- Click open the select again and you see eee and ggg selected.

See https://jsfiddle.net/cybuydm0/

**Comment by acburst** [comment]
Fixed in 7b67132

**Comment by nighthawk469** [comment]
This is still broken for me in 0.100.1.
When using optgroups and multiple, the select behaves strangely and returns the wrong values.
