### ISSUE TITLE
Data-Error attribute wraps text once it reaches the length of the label

### ISSUE THREAD

**Issue by Native-Coder** [Dogfalo/materialize#4333]
### Description
When using a custom Data-Error message, if the error message is longer than the label string, the error message will wrap at the length of the label.

### Repro Steps
Add a data-error attribute to the label of any input element. (make sure the data-error attribute is LONGER than the text used for the label)

To work around the issue I added kept adding `&nbsp;` to the label until the label was long enough to encompass the error.

Perhaps this is desired behavior, But I expected the data-error to start wrapping at the length of the input line, not the length of the label.

### Screenshots / Codepen
Here is a codepen illustrating the issue and how I worked around it. [codepen](http://codepen.io/anon/pen/wJJGYR) (Enter text in either field to get the error message to appear)

![capture](https://cloud.githubusercontent.com/assets/22647295/23774339/d3679720-04e8-11e7-8f1d-6d73e8ee601a.PNG)

**Comment by Native-Coder** [comment]
bump?

**Comment by Dogfalo** [comment]
Fixed in v0.99.0

**Comment by smileytechguy** [comment]
v0.100.2 seems to still have this error...this can be seen in @Native-Coder's codepen by changing the assets to use the latest version.

**Comment by smileytechguy** [comment]
Adding the following to my override CSS solves the issue:

```css
label[data-error], label[data-success] {
	width: 100%;
}
```

**Comment by Dogfalo** [comment]
I believe there was a regression here because we had to revert this change because it was causing some other bugs. We changed the way we handle the error messages in 1.0 so that it is a separate element and does not have this problem.

**Comment by smileytechguy** [comment]
Alright, thanks

**Comment by Dogfalo** [comment]
Here is what the new error message system will look like

```html
<div class="input-field inline">
    <input id="email" type="email" class="validate">
    <label for="email">Email</label>
    <span class="helper-text" data-error="wrong" data-success="right">Helper text</span>
</div>
```

**Comment by smileytechguy** [comment]
Oh, I like that.  That's about how I'm doing it for things like recaptcha and stuff already
