### ISSUE TITLE
.active not applied to already-filled inputs

### ISSUE THREAD

**Issue by mz3** [Dogfalo/materialize#434]
![screenshot](http://emzy.cc/up/1420923321.png)

Autocomplete, for example.

**Comment by Dogfalo** [comment]
This is fixed already and will be available in the next release

[image: screenshot]
<https://camo.githubusercontent.com/4c5339c1e01a44f955427ea07041636eeff02f0d/687474703a2f2f656d7a792e63632f75702f313432303932333332312e706e67>

Autocomplete, for example.

—
Reply to this email directly or view it on GitHub
<https://github.com/Dogfalo/materialize/issues/434>.

**Comment by ToX82** [comment]
I'm still having the same issue here, using both 0.97 release and the latest, today commit.

The label goes in the right position only when I click anywhere on the page.
