### ISSUE TITLE
FeatureDiscovery doesn't align to the bottom on mobile devices (v0.98.1)

### ISSUE THREAD

**Issue by CodeSurfing145** [Dogfalo/materialize#4487]
### Description
The FeatureDiscovery function does algin on Desktop/Laptop but not on mobile devices.

### Repro Steps
Open http://materializecss.com/feature-discovery.html and click on OPEN TAP TARGET
Now try again on Android phone (Not sure about iPhones bahh)

### Screenshots / Codepen
PC: 

![screenshot from 2017-04-04 08-37-53](https://cloud.githubusercontent.com/assets/6624832/24644086/0467d8de-1912-11e7-8622-5b1c35b05310.png)

Android:

![screenshot_20170404-083841](https://cloud.githubusercontent.com/assets/6624832/24644231/ac37ceb6-1912-11e7-8d60-5bc5f3011a85.png)

**Comment by CodeSurfing145** [comment]
![screenshot_20170404-100202](https://cloud.githubusercontent.com/assets/6624832/24646911/e9ae86b2-191d-11e7-9bbc-60e246edefad.png)
Landscape mode seems to align it correctly except for the title and the text.

**Comment by DanielRuf** [comment]
related, fixed width and height for all views under 600px
![image](https://cloud.githubusercontent.com/assets/827205/24655334/1feaf9ac-193e-11e7-9214-d59aaad1cf43.png)

**Comment by inventti-leonardo** [comment]
@DanielRuf @CodeSurfing145 @fega  

I think was fixed here https://github.com/Dogfalo/materialize/issues/4378

**Comment by DanielRuf** [comment]
This does not fix it, still the same since the last build https://github.com/Dogfalo/materialize/commit/0407ee5352271de822cade662353319f6eebe5c8

Also the 600px value seems probleamtic.

**Comment by DanielRuf** [comment]
Open it in desktop and resize to a lower screen width
![image](https://cloud.githubusercontent.com/assets/827205/24658598/6ed0d256-194a-11e7-96f8-ab62e6566a33.png)

**Comment by DanielRuf** [comment]
Directly opened in small view
![image](https://cloud.githubusercontent.com/assets/827205/24658658/a7b8387a-194a-11e7-8929-7ecd684893e1.png)

**Comment by DanielRuf** [comment]
Different behaviour if you start opened or closed.

**Comment by acburst** [comment]
It looks like you are viewing the current site right? This issue has been fixed but is not in the current release. It won't show up in the actual site until we release a new version.

**Comment by DanielRuf** [comment]
> It looks like you are viewing the current site right? This issue has been fixed but is not in the current release. It won't show up in the actual site until we release a new version

You reference http://materializecss.com/css/ghpages-materialize.css and http://materializecss.com/bin/materialize.js on the website. The screenshots are new

The fix is older (8 days) than the build date of these two files (now 14 hours and 4 days).
https://github.com/Dogfalo/materialize/commits/master?after=0e13b80f6bfee1700dd2c2aa49494a44c8a61acb+34

Steps to reproduce:
* open the website in normal desktop / full width
* click the open button
* resize the window
and
* open the website in small mobile view
* click the open button
* resize the window

**Comment by acburst** [comment]
The website version is hosted on a different branch (gh-pages). So those compiled files will still be the old versions.

**Comment by DanielRuf** [comment]
https://github.com/Dogfalo/materialize/pull/4416
> acburst merged commit 132f71e into Dogfalo:master 6 days ago

**Comment by tomscholz** [comment]
@DanielRuf We use the `gh-pages` branch for github pages hosting. With every version bump, we merge the master into the gh-pages branch

**Comment by DanielRuf** [comment]
> The website version is hosted on a different branch (gh-pages). So those compiled files will still be the old versions.

Ok but why not switch to the master branch for the page like @tomscholz recommended?

**Comment by DanielRuf** [comment]
> I agree that 600px maybe be problematic, but works for now :(

At least still issues on smaller screens? Ok.

**Comment by DanielRuf** [comment]
Switching portrait / landscape
![image](https://cloud.githubusercontent.com/assets/827205/24663170/6c556354-1957-11e7-935f-973face0ef89.png)

**Comment by tomscholz** [comment]
> Ok but why not switch to the master branch for the page like @tomscholz recommended?

@DanielRuf No, I never said that. I just meant, that the fix is working when you have a look at the master branch and to illustrate that, I used rawgit.com. That isn't a good idea at all, because then everyone would see the docs that are incomplete. Do you understand where I'm getting with this?

**Comment by DanielRuf** [comment]
> Ok but why not switch to the master branch for the page like @tomscholz recommended?
> @DanielRuf No, I never said that. I just meant, that the fix is working when you have a look at the master branch and to illustrate that, I used rawgit.com. That isn't a good idea at all, because then everyone would see the docs that are incomplete. Do you understand where I'm getting with this?

Right but there is still the illustrated issue, even on the master branch.
It was just a CSS fix.

**Comment by acburst** [comment]
You always want some separation between code commits and the production site. Otherwise the site would break all the time.

**Comment by inventti-leonardo** [comment]
@acburst I fixed the issue reported by @DanielRuf above

Thanks for catching

**Comment by DanielRuf** [comment]
> @acburst I fixed the issue reported by @DanielRuf above
> 
> Thanks for catching

Yep, fixed.
You are welcome.

At the beginning I thought you fixed this and then saw that it was an extra bug that I found and I might have been a bit unclear (could have communicated it better) and we talked past each other :D

**Comment by acburst** [comment]
Merged
