### ISSUE TITLE
Dynamically created textarea is not resizing

### ISSUE THREAD

**Issue by TetianaP** [Dogfalo/materialize#4613]
### Description
When textarea control is created dynamically, auto-resize is not fired.
`$('.materialize-textarea').trigger('autoresize');` won't help, as textarea does not have `autoresize` event bound to it. The only time it is set - is `$(document).ready`.

Maybe you can add some initialization for dynamically created controls, similar to what we can use for `select `elements -` $('select').material_select();` ?

**Comment by DanielRuf** [comment]
https://github.com/Dogfalo/materialize/blob/master/js/forms.js#L179-L181

http://api.jquery.com/on/
> When a `selector` is provided, the event handler is referred to as *delegated*. The handler is not called when the event occurs directly on the bound element, but only for descendants (inner elements) that match the selector. jQuery bubbles the event from the event target up to the element where the handler is attached (i.e., innermost to outermost element) and runs the handler for any elements along that path matching the selector.

For me it seems it works: http://codepen.io/anon/pen/mmRLwL

But there is just an issue with the label.

**Comment by TetianaP** [comment]
It is working fine for the version 0.98.1 (the one you used in your example), but it does not work for the latest one - 0.98.2.

**Comment by DanielRuf** [comment]
@TetianaP you are right, seems we have another regression bug here.

http://codepen.io/anon/pen/QvpdNM

Would have to compare the compiled components and triage this bug.

**Comment by DanielRuf** [comment]
Seems we have to add a check for `data('original-height') === undefined` or similar.

http://codepen.io/anon/pen/QvpdvO

**Comment by DanielRuf** [comment]
@fega @tomscholz please add a label like `needs-pr` so I know that I plan to create a PR.

**Comment by tomscholz** [comment]
@DanielRuf I don't think that we need a `needs-pr` label. I mean, pull request are always welcome and such a label would would make things more complicated than necessary

**Comment by DanielRuf** [comment]
@tomscholz ok. Will add the issue number to my personal todo list.

**Comment by DanielRuf** [comment]
@TetianaP please test the change and if this breaks nothing

**Comment by acburst** [comment]
Fixed in 4a3c15c

**Comment by DanielRuf** [comment]
> Fixed in 4a3c15c

No this does not fix this if the data attribute is undefined / missing (at least in Chrome).
https://github.com/Dogfalo/materialize/issues/4621

**Comment by DanielRuf** [comment]
d is not shown if the data attribute is undefined

![image](https://cloud.githubusercontent.com/assets/827205/25589712/f153be1e-2ead-11e7-9f94-97e6275ab993.png)

d is shown if the data attribute is defined

![image](https://cloud.githubusercontent.com/assets/827205/25589757/1ff55af2-2eae-11e7-8d08-d9619ea3763f.png)

d is shown with https://github.com/Dogfalo/materialize/issues/4621

![image](https://cloud.githubusercontent.com/assets/827205/25589807/4f0ef870-2eae-11e7-82cc-01be8ff2da5f.png)

**Comment by TetianaP** [comment]
@DanielRuf that works, thanks everyone!
How soon could we expect it to be released?

**Comment by DanielRuf** [comment]
@TetianaP you could also use one of the solutions

http://stackoverflow.com/a/16951315/753676
http://stackoverflow.com/a/18049685/753676

should also work with the update command

**Comment by TetianaP** [comment]
@DanielRuf  Thanks, it will work, but in this case need to bundle all `js` together, as `materialize-css/dist/js/materialize.min.js` was not updated and it contains old implementation from `forms.js`.

**Comment by DanielRuf** [comment]
@TetianaP just clone and run Grunt in the directory of Materialize to build a new file using the js_compile task.

**Comment by eduardoalvara2** [comment]
`set data-original-height=0`

 worked for me with the version 0.98.2

**Comment by DanielRuf** [comment]
Exactly ;-) https://github.com/Dogfalo/materialize/issues/4613#issuecomment-297950328

**Comment by ZiperRom1** [comment]
Hi same problem here on version `v0.99.0`

- I add a textarea dynamically to the DOM
- I set its value with `$('#myTextArea').val($('#myTextArea').attr('data-original-value'));`
- I trigger the autoresize event `$('#myTextArea').trigger('autoresize');`

The data-label overlasped the text, if I click on the textarea the label goes correctly on top the text and all goes fine then.

The HTML

```ejs
<div class="row">
    <div class="input-field col s12">
        <textarea id="bot-message-input"
                  class="materialize-textarea"
                  data-original-value="<%= text %>"
                  data-original-height="0"></textarea>
        <label for="bot-message-input">The message the bot will print</label>
    </div>
</div>
```

The bug state at the page load

![textarea-bug-state](https://user-images.githubusercontent.com/10369248/27847787-3810fb68-6140-11e7-880c-8d9f23adbaae.png)

The ok state after clicking on the textarea

![text-area-ok-state](https://user-images.githubusercontent.com/10369248/27847788-3825b170-6140-11e7-866f-7bf30720cc40.png)

**Comment by knight7024** [comment]
i have a same problem

**Comment by knight7024** [comment]
@DanielRuf I have a same problem on 0.99.0

**Comment by DanielRuf** [comment]
@knight7024 did you try 0.100.0 or newer?

**Comment by knight7024** [comment]
@DanielRuf yes im doing it now but nothing changed

**Comment by SmboBeast** [comment]
Is anyone else still having this problem?  I just upgraded from .98 to .100.2 and this is an issue.  It wasn't an issue in the .98 version.

Any help would be appreciated.

**Comment by knight7024** [comment]
@SmboBeast I'm using .100.1 version materialize javascript because of this issue. Have you imported js in body tag?

**Comment by SmboBeast** [comment]
@knight7024 

Thank you for this!  I will try using .100.1 right now and see if this is a temporary fix.  

I have imported the JS in the body tag also.  Give me a few minutes.  Will update this thread.

**Comment by SmboBeast** [comment]
@knight7024 Even on .100.1, it still doesn't work for me on page load.  However, when text is entered into the textarea, it works just fine.  Weird...

**Comment by knight7024** [comment]
Well... idk about that issue. We need to wait newer version which is fixed

**Comment by SmboBeast** [comment]
Agreed.  Thanks @knight7024

**Comment by knight7024** [comment]
:) @SmboBeast

**Comment by 653579487** [comment]
M.textareaAutoResize(document.querySelector('.materialize-textarea'))
