### ISSUE TITLE
Material Box not Responsive

### ISSUE THREAD

**Issue by pingshunhuangalex** [Dogfalo/materialize#4706]
### Description
I tried to use material box sitting in the media category. The animation looks smooth and it's exactly what I want. However, when I'm testing the responsiveness by resizing window while the image is enlarged, things just go all over the place. This becomes particularly bad when I resize small window to a bigger one.

Please make the material box responsive, or at least let the material box exit itself when it detects windows size change.  Thanks.

### Repro Steps
1. Just use the examples exhibited on your website
http://materializecss.com/media.html
2. Trigger material box by clicking on the image
3. resize browser window from big to small (or trigger material box at a smaller screen and resize the window to a bigger one)
4. Things go crazy (i.e. black overlay not covering the whole window, images not centered and misplaced, etc.).

### Screenshots / Codepen

![image](https://cloud.githubusercontent.com/assets/17170199/26227845/6ae56070-3c78-11e7-9a80-e07de91645e5.png)

**Comment by DanielRuf** [comment]
Right. overlay and origin have to listen on window.resize and window.orientationchange and recalculate them. Also the width and height of the overlay should be possibly 100% each.

**Comment by pingshunhuangalex** [comment]
@DanielRuf Is this gonna be an easy fix?
I'm not going to rush you guys. I just want to know whether this will be fixed soon so I can decide if I should use this feature on one of my current projects or try to write my own. Thanks.

**Comment by DanielRuf** [comment]
This is a good question. We would have to first find the affected lines (I may have found some), discuss the best solution and prepare a PR.

**Comment by DanielRuf** [comment]
https://github.com/Dogfalo/materialize/blob/7c2527cd8be60b840ae7ad1faefd3b8f0d91b385/js/materialbox.js#L144-L150

https://github.com/Dogfalo/materialize/blob/7c2527cd8be60b840ae7ad1faefd3b8f0d91b385/js/materialbox.js#L163-L170

https://github.com/Dogfalo/materialize/blob/7c2527cd8be60b840ae7ad1faefd3b8f0d91b385/js/materialbox.js#L102-L106

**Comment by acburst** [comment]
I feel like a simpler solution would be to just close the materialbox on window resize. The complexity of keeping everything perfect during a resize isn't worth it in my opinion

**Comment by DanielRuf** [comment]
But this would require to close it also on orientation change and so on too.

Is this the desired behavior? I'm unsure because this issue is fixable imo.

**Comment by acburst** [comment]
Fixed in 5b71e27

Added an exit with window resize. I've also made the other handlers more efficient as they will only be added and removed when a materialbox is activated.

And I think this should be the desired behavior for resizing. If there is a distinct and supported way to detect only mobile orientation changes then I would be open to it, but I don't know of any.

**Comment by DanielRuf** [comment]
> If there is a distinct and supported way to detect only mobile orientation changes then I would be open to it, but I don't know of any.

Something like [this](https://stackoverflow.com/a/9824480/753676)?

**Comment by pingshunhuangalex** [comment]
Hi @acburst 
Just wondering has this change been pushed to `master` yet, i.e. can I use it in the form of a cdn? I just check the `media` sample on the website, and it still doesn't seem to be fixed. Thanks.

**Comment by DanielRuf** [comment]
See https://github.com/Dogfalo/materialize/commit/5b71e271a5126c58b7b725e58a1af76933b71303

And no, this is probably not available on the CDN as it uses tagged releases afaik. You may have to clone the repository and compile with Grunt.
