### ISSUE TITLE
Size of textarea not changing on page load with default content

### ISSUE THREAD

**Issue by bastones** [Dogfalo/materialize#4757]
### Description
When I use a `.materialize-textarea` textarea element on a page, Materialize does not expand the textarea to display all of the content that might already be present in the textarea when the page is loaded.

### Repro Steps
Add `<textarea class="materialize-textarea">...</textarea>` with several paragraphs of dummy content.

I have noticed this issue is not reproducible in 0.98.1 but is in 0.98.2, as below:

0.98.1: https://codepen.io/anon/pen/rwNbLz
0.98.2: https://codepen.io/anon/pen/bRGJwd

### Screenshots

**On page load:**

<img width="1335" alt="screen shot 2017-06-04 at 14 20 59" src="https://cloud.githubusercontent.com/assets/845891/26762068/5ce82a30-4933-11e7-995b-67fb0d76d188.png">

**On keydown:**

<img width="1283" alt="screen shot 2017-06-04 at 14 21 04" src="https://cloud.githubusercontent.com/assets/845891/26762072/639f13fc-4933-11e7-90c8-ba59cf2674c5.png">

**Comment by tomscholz** [comment]
Fixed in https://github.com/Dogfalo/materialize/commit/4a3c15c9fcd1bdd778f2840e932700254522fda7

**Comment by bastones** [comment]
Dude, that was one quick reply. Thank you.

**Comment by jer8** [comment]
Hi, I'm still facing this issue with React when rendering a component with textarea. Here's my html:

``` html

<div className="input-field">
    <textarea id="notes-textarea" defaultValue={this.state.notes} className="materialize-textarea sticky-textarea" onChange={this.handleNotesChange}></textarea>
    <label htmlFor="notes-textarea" className="active">Notes</label>
</div>
```

I'm using v0.99.0.
