### ISSUE TITLE
Responsive tables

### ISSUE THREAD

**Issue by ventouris** [Dogfalo/materialize#488]
I downloaded again the files and now the tables are responsive. However, the way it shows doesn't fit with my style. They turn horizontally and show only 3-4 columns. Is there any way to disable it?

**Comment by jzetina** [comment]
I have a similar problem, I have a table with only two columns and the way is shown in mobile doesn't look good. How can I remove responsiveness of that specific table?

**Comment by acburst** [comment]
Fixed in 792e079eb2393e7ad00cf0d22520790dfc6a4d67

Now it is tied to the class .responsive-table

**Comment by ventouris** [comment]
I downloaded the new package from the website and the table has still the same behavior. Even without the .responsive-table

**Comment by acburst** [comment]
It's not in the downloadable package. You will have to download straight from our git repo. It will be in the next release.
