### ISSUE TITLE
Function getWavesEffectElement throwing TypeError when clicking on SVGs

### ISSUE THREAD

**Issue by KoltonG** [Dogfalo/materialize#537]
**Description:** When clicking on a SVG element, the getWaveEffectElement is being called and it throws a "Uncaught TypeError: undefined is not a function" when trying to call **.className.indexOf('waves-effect')** on the SVG element (when target = an SVG Element).

``` javascript
while (target.parentElement !== null) {
            if (target.className.indexOf('waves-effect') !== -1) {
                element = target;
                break;
            }
            target = target.parentElement;
}
```

**Comment by Dogfalo** [comment]
You want to wrap the svg in either a <a> or <div> tag. Applying it directly on SVG is not supported

**Comment by agegorin** [comment]
I have the same problem. And I am not applying anything from materialize to SVG.
Try click on X here: http://jsfiddle.net/agegorin/cqLfj61f/

Function called on all click on body element and if target is svg then event.target will have no className property.

**Comment by KoltonG** [comment]
@Dogfalo the issue is still persisting on my side event though my SVG elements are wrapped in Divs

**Comment by canweriotnow** [comment]
@Dogfalo The problem isn't _applying_ it on an SVG, it's getting the handler to _ignore_ clicks on SVG elements and thus breaking everything.

**Comment by Dogfalo** [comment]
I see, I misunderstood the problem. If you need it work right now, I would just add a handler to capture the event and stopPropagation of the event.

```JS 
element.addEventListener("click", functionWithStopPropagation, true);
```

**Comment by canweriotnow** [comment]
@Dogfalo yeah, I was trying to think of a workaround until this is either resolved here or in waves.js itself, the tricky bit is with things like interactive graphs that render as SVG or canvas elements catching the event propagation at exactly the right point... I'll play with it tomorrow. Thanks!

**Comment by Dogfalo** [comment]
Should be fixed by 49db61bc679970e215c5769e0668f924157b5d10

**Comment by Dogfalo** [comment]
Can someone confirm that this is fixed by testing the build in bin/? That way we can have this fixed for next build.

**Comment by pickeloe5** [comment]
I'm using version 0.99.0, the problem still exists. Clicking on an SVG causes an error:
`c.className.indexOf is not a function`
