### ISSUE TITLE
Multiple select – placeholder option handling

### ISSUE THREAD

**Issue by vuhrmeister** [Dogfalo/materialize#5463]
If I want to show a "placeholder" option for the field not being empty when nothing selected, this option will be displayed even if other options are selected.

Though this is the proper default HTML behavior it doesn't make any sense.

You can reproduce it with the example of the documentation:

<img width="716" alt="bildschirmfoto 2017-12-12 um 10 31 16" src="https://user-images.githubusercontent.com/2188790/33877115-adbf53d6-df27-11e7-8692-f4b52c4f67c6.png">

The "Choose your option" should not be displayed after selection.

A better approach could be to make floating labels work with select fields. Probably it also doesn't cover all scenarios, but for me that would be fine.

## Your Environment
* Version used: 1.0.0-alpha.2

**Comment by acburst** [comment]
Fixed in 32e6138b.

**Comment by kamalrahimi** [comment]
@acburst hi . how can i fix this bug in my codes?

**Comment by Romej** [comment]
This issue has not been fixed.
Even in the docs, the multiple select still shows "Choose your option" after you select one or many options.
https://materializecss.com/select.html

**Comment by enemeth19** [comment]
The problem originally described by @vuhrmeister has still not been fixed! Can you please re-open this issue?

**Comment by jdalrymple** [comment]
As @Romej mentioned, this issue still persists

**Comment by afandino-sg** [comment]
You'd have to deselect the default option with JavaScript when any option gets marked and select it again when no other option is selected.
