### ISSUE TITLE
Autocomplete on chips does not work anymore in RC1

### ISSUE THREAD

**Issue by pwittke** [Dogfalo/materialize#5884]
When you type in a title for a chip, the autocomplete does not trigger properly anymore.

Only when you type on the input field near or on your text again, you get the autocomplete options to show.

This can be reproduced on the documantation page itself:
http://materializecss.com/chips.html

When you type in e.g. "google" nothing happens, until you click on the text a second time.

**Affected Version:** 1.0.0-rc.1

**Browsers:**
Chrome 66.0.3359.139
Firefox 59.0.3
Opera 52.0.2871.99

**Comment by kasperrt** [comment]
Same thing happens in http://materializecss.com/autocomplete.html page. Have to click out of input-field for it to pop-up.

**Comment by acburst** [comment]
Fixed in ac5c80e3

**Comment by AlbertoDrusiani** [comment]
Guys it's not fixed. The problem still occurs on your page, chips autocomplete and form autocomplete too.

**Comment by DeweyOx** [comment]
After applying this fix (it does work for the posted issue) it exposes another issue. The item click handler only fires the second time. The first time, the options close and nothing else happens. The second time, the option populates the input as expected.

**Comment by pwittke** [comment]
The fix provided by acburst worked for me and fixed the issue I just added the changes to my local copy.
