### ISSUE TITLE
Parallax Jumps On Load

### ISSUE THREAD

**Issue by awhedbee22** [Dogfalo/materialize#628]
When the page is first loaded, the image is pushed to the top, and then once user scrolls it jumps into proper position. I have my example locally but it does it on the demo page as well.

Windows 7 - Chrome v40

**Comment by mcbejn** [comment]
Same happening for me right now. Got the newest version from Github, I thought the issue was resolved. 
The image gets pushed upward by what seems to be exactly the number of pixels it should be pushed downward. 

Will try to fix myself and if I get something I'll post the fix here

**Comment by mcbejn** [comment]
Seems like I fixed it
I know it's not the best way since I edited materialize.js directly, but here goes:

locate line 838 

 $this.addClass('parallax');

and right after that add:

$this.children("img").css('bottom',0); // parallax fix

This sets the initial position of the parallax images to normal

**Comment by acburst** [comment]
Fixed in f0b7f16122576beaa36cd8e0dcff38950c8018ab

**Comment by awhedbee22** [comment]
Great work Guys! Thanks for the quick fix.

**Comment by brunomiguel** [comment]
Using Chromium and Firefox on Ubuntu 14.10 and this bug still persists

**Comment by carloscarcamo** [comment]
I have the same problem, is supposed that the last version of materialize fix this problem but it seems that it does not.

see here:

First load
![1](https://cloud.githubusercontent.com/assets/2413746/6647453/f93daa58-c993-11e4-994a-dd23498ae33f.png)

it should look like this
![2](https://cloud.githubusercontent.com/assets/2413746/6647460/13d7c15a-c994-11e4-9182-3dd4dfced3ff.png)

How can I fix this problem? 

I'm using ubuntu with Firefox v35

**Comment by Dogfalo** [comment]
Do you have a test url I can see?

**Comment by carloscarcamo** [comment]
Sorry, right now is on local folder only, maybe later I can use a host for test so you can see the problem there...
