### ISSUE TITLE
Modals should have a white background

### ISSUE THREAD

**Issue by nahtnam** [Dogfalo/materialize#965]
Hey!

Modals should have a white background instead of gray. http://www.google.com/design/spec/components/dialogs.html

Thanks.

**Comment by Dogfalo** [comment]
Fixed in de5346005926008af887846ed3a8ff947d0542c1

**Comment by nahtnam** [comment]
Awesome! Thanks a lot! :)

**Comment by nahtnam** [comment]
@Dogfalo Not completely fixed. You also need to change the background color of the footer. Can make a PR if you want.

**Comment by Dogfalo** [comment]
It was changed a few commits later

**Comment by nahtnam** [comment]
Right. Thanks.
